# Generated by Django 2.2 on 2019-04-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderer', to='UIApp.User'),
        ),
    ]
