# Generated by Django 2.2 on 2019-04-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_auto_20190411_1408'),
        ('UIApp', '0002_auto_20190406_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='carter', to='AdminApp.Product'),
        ),
    ]
